### ISSUE TITLE
Invalid manifest on install

### ISSUE THREAD

**Issue by surajiyer** [yujily/sesh#1]
Get an "Invalid manifest" error on install. Might be due to updated manifest requirements. background should also specify key "persistent".

Chrome Version 67.0.3396.79 (Official Build) (64-bit)

**Comment by yujiberra** [comment]
Thanks for bringing this up. I wasn't able to reproduce this exact issue, but you were right about background and persistence, which also led to me making a couple other minor changes, after which I was able to submit a new, working version to the web store. So I'm closing this issue, but if you continue to encounter it I can reopen it.
