### ISSUE TITLE
Apply an open-source licence to this project?

### ISSUE THREAD

**Issue by 0xdevalias** [yujily/sesh#2]
Firstly, I wanted to say thanks for making Sesh. It's simple, but it's simplicity is what makes it so useful! It has been one of my most used chrome extensions since at least 2013. I actually ended up writing/releasing my own chrome extension back then to make my tab habit easier to manage using Sesh:

- https://www.devalias.net/devalias/2013/08/08/new-window-with-tabs-to-right-chrome-extension/

I've had a vague idea of wanting to add some features to this that 'play nice' with Sesh (eg. https://github.com/0xdevalias/chrome-NewWindowWithTabsToRight/issues/6), where it would be useful to be able to use bits of code from this repo.

Though I noticed that this project doesn't have any `LICENCE` file, which effectively makes it 'no permission', as per:

- http://opensource.guide/legal/#are-public-github-projects-open-source

I was wondering if you would be open to applying an open-source licence to it?

- http://opensource.guide/legal/#just-give-me-the-tldr-on-what-i-need-to-protect-my-project
- https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository

Personally, I tend to use the MIT Licence for my open-source projects, as it's short, simple, and easy to understand:

- https://choosealicense.com/licenses/mit/
- eg. https://github.com/0xdevalias/chrome-NewWindowWithTabsToRight#license

**Comment by yujiberra** [comment]
Thanks for getting in touch! It makes me very happy to hear that you've found my little browser extension useful :)

It never occurred to me that anyone might be interested in this code, but yeah I'm totally in favor of open sourcing things so I just added a license file with the MIT License. Thanks for sharing those links and making it extra easy!

**Comment by 0xdevalias** [comment]
Amazing! Thanks for doing that!
